name: CI

on:
  push:
    branches:
      - dev
      - 'feat/**'

permissions:
  contents: write
  pull-requests: write
  repository-projects: write

env:
  NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

jobs:
  run-test:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - name: download codes
        uses: actions/checkout@v4
        # with:
        # persist-credentials: false

      - name: install dependencies
        run: npm install

      - name: run test
        run: npm run test

      - name: run build
        run: npm run build

  create-pr:
    needs: run-test
    name: Create PR
    runs-on: ubuntu-latest
    steps:
      - name: download codes
        uses: actions/checkout@v4
        # with:
        # persist-credentials: false

      # - name: set git config
      # run: |
      # git config --global user.email "bdohhhhh@gmail.com"
      # git config --global user.name "eunohhh"
      # git remote set-url origin https://${{ secrets.ACCESS_TOKEN_FOR_CI }}@github.com/${{ github.repository }}

      - name: create pr
        uses: peter-evans/create-pull-request@v7
        with:
          # token: ${{ secrets.ACCESS_TOKEN_FOR_CI }}
          base: main # 머지 대상은 main
          branch: ${{ github.ref }}
          title: 'chore: dev -> main'
          body: 'Auto PR'
